# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: clippy
        args:
        - "--"
        - "-D"
        - "warnings"
