# .woodpecker/rust-check.yaml

# Defines when this pipeline should run.
# It triggers on pushes and pull requests to the 'dev' branch.
when:
  branch: dev
  event: pull_request

# Defines the sequence of steps in the pipeline.
# Steps run sequentially by default.
steps:
  - name: cargo-fuzz test
    image: alpine@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
    commands:
      - apk add --no-cache curl gcc build-base musl-dev
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal --default-toolchain nightly -y --no-modify-path
      - export PATH="$HOME/.cargo/bin:$PATH"
      - rustup override set nightly
      - rustup default nightly
      - rustc +nightly --version
      - cargo +nightly --version
      - cargo install cargo-fuzz
      - cargo +nightly fuzz run ​​--sanitizer none fuzz_parse_duration
      - cargo +nightly fuzz run ​​--sanitizer none fuzz_toml_parser
